"""Shared defaults for configuration and runtime behavior."""

DEFAULT_HOST = "0.0.0.0"
DEFAULT_PORT = 8000
DEFAULT_RELOAD = True
MAX_TURNS = 3

WHISPER_MODEL_NAME="small"
WHISPER_DEVICE="cpu"
WHISPER_COMPUTE_TYPE="int8"
WHISPER_LANGUAGE="en"


QUESTIONS_PER_LEVEL=1
MIN_PASSED_FOR_LEVEL=0
MAX_FOLLOWUP_QUESTIONS=2

# LLM Configuration
LLM_MODEL="gpt-4o-mini"
LLM_TEMPERATURE=0.3

# API Timeouts (seconds)
API_TIMEOUT=120

# Audio Configuration
AUDIO_SAMPLE_RATE=16000




